language: scala
scala:
- 2.10.4
jdk:
- openjdk7
before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx3g"
after_success:
- sbt publishMasterOnTravis
cache:
  directories:
    - $HOME/.ivy2/cache
